name: Process Real Estate Deals

on:
  schedule:
    # Run every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  process-deals:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run configuration test
      env:
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
      run: |
        python test_config.py
        
    - name: Process new deals
      env:
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
      run: |
        python main.py
        
    - name: Upload processed emails log
      if: always()  # Upload even if script fails
      uses: actions/upload-artifact@v3
      with:
        name: processed-emails-log
        path: processed_emails.json
        retention-days: 7